# Generated by Django 5.0.6 on 2024-09-16 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Environment', 'Environment'), ('Exercise', 'Exercise'), ('Health', 'Health'), ('Sentiment', 'Sentiment'), ('Nutrition', 'Nutrition'), ('Hobby', 'Hobby')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('For 1 week', 'For 1 week'), ('For 2 weeks', 'For 2 weeks'), ('For 3 weeks', 'For 3 weeks'), ('For 4 weeks', 'For 4 weeks')], default='For 1 week', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_data', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='habit_stacker.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
