# Generated by Django 5.0.6 on 2024-09-17 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stacker', '0004_alter_challengeparticipant_user_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeparticipant',
            unique_together={('user', 'challenge')},
        ),
    ]
