# Generated by Django 5.0.6 on 2024-09-17 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stacker', '0005_alter_challengeparticipant_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeparticipant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='challengeparticipant',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_user_challenge'),
        ),
    ]
